# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5023ba5b2be9644f3416480c06970d166cac3c1637f4e7fb41a951586c6e0704cb71200bed91b2e47e44bfd18d1f23a235285f025e4fb75d8e8429b1e29b5e27

test:
  secret_key_base: 72a40f85e175521e1b82d2364c4d964b59d3bfa5046591bccff9ae42717255777132938014cd2c9385661d9b6edc61216f94ee46ddb167e78400adc2232bce34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
